"""Add transaction_type enum

Revision ID: 51a966e31aa3
Revises: 5c30fe6c1a01
Create Date: 2025-11-04 13:16:54.324694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a966e31aa3'
down_revision: Union[str, Sequence[str], None] = '5c30fe6c1a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE transactiontype AS ENUM ('INCOME', 'COST')")
    
    # Then add the column
    op.add_column('transactions', sa.Column('transaction_type', 
                  sa.Enum('INCOME', 'COST', name='transactiontype'), 
                  nullable=False))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_type')
    
    # Then drop the enum type
    op.execute("DROP TYPE transactiontype")
    # ### end Alembic commands ###
