name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            cd ~/costs_project

            echo ">>> Pulling latest code..."
            git pull origin main

            echo ">>> Creating/Updating .env file..."
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
            echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            
            echo ">>> Building new images..."
            docker-compose build --no-cache app bot

            echo ">>> Restarting services..."
            docker-compose up -d --force-recreate --no-deps app bot

            echo ">>> Pruning old Docker images..."
            docker image prune -a -f
